/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MockupsRouteImport } from './routes/mockups'
import { Route as IndexRouteImport } from './routes/index'

const MockupsRoute = MockupsRouteImport.update({
  id: '/mockups',
  path: '/mockups',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mockups': typeof MockupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mockups': typeof MockupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mockups': typeof MockupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mockups'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mockups'
  id: '__root__' | '/' | '/mockups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MockupsRoute: typeof MockupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mockups': {
      id: '/mockups'
      path: '/mockups'
      fullPath: '/mockups'
      preLoaderRoute: typeof MockupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MockupsRoute: MockupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
